import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";

export async function GET(
  req: Request,
  { params }: { params: Promise<{ grantId: string }> }
) {
  const session = await auth();
  if (!session?.user?.id) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { grantId } = await params;
  const { searchParams } = new URL(req.url);
  const format = searchParams.get("format") ?? "txt";

  const grant = await prisma.grant.findUnique({
    where: { id: grantId },
    include: {
      organization: true,
      funder: true,
      sections: { orderBy: { sortOrder: "asc" } },
    },
  });

  if (!grant) return Response.json({ error: "Not found" }, { status: 404 });

  const membership = await prisma.orgMembership.findUnique({
    where: {
      userId_organizationId: {
        userId: session.user.id,
        organizationId: grant.organizationId,
      },
    },
  });
  if (!membership) return Response.json({ error: "Forbidden" }, { status: 403 });

  const safeName = grant.title.replace(/[^a-z0-9]/gi, "_");

  if (format === "pdf") {
    try {
      const buffer = await buildPDF(grant);
      return new Response(new Uint8Array(buffer), {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${safeName}.pdf"`,
        },
      });
    } catch (err) {
      console.error("PDF build error:", err);
      return Response.json({ error: "Failed to generate PDF." }, { status: 500 });
    }
  }

  if (format === "docx") {
    try {
      const buffer = await buildDocx(grant);
      return new Response(new Uint8Array(buffer), {
        headers: {
          "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "Content-Disposition": `attachment; filename="${safeName}.docx"`,
        },
      });
    } catch (err) {
      console.error("DOCX build error:", err);
      return Response.json({ error: "Failed to generate DOCX." }, { status: 500 });
    }
  }

  // Default: TXT
  return new Response(buildTxt(grant), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${safeName}.txt"`,
    },
  });
}

function buildTxt(grant: any): string {
  const lines: string[] = [];
  lines.push("=".repeat(70));
  lines.push(grant.title.toUpperCase());
  lines.push(`Applicant: ${grant.organization.name}`);
  lines.push(`Funder: ${grant.funder.name}`);
  if (grant.requestedAmount) lines.push(`Amount Requested: $${Number(grant.requestedAmount).toLocaleString("en-CA")}`);
  if (grant.deadline) lines.push(`Deadline: ${new Date(grant.deadline).toLocaleDateString("en-CA")}`);
  lines.push(`Compliance Score: ${grant.complianceScore ?? "Not checked"}/100`);
  lines.push("=".repeat(70));
  lines.push("");
  for (const s of grant.sections) {
    if (!s.content) continue;
    lines.push(s.label.toUpperCase());
    lines.push("-".repeat(s.label.length));
    lines.push(s.content);
    lines.push(`\n[${s.wordCount} words]\n`);
  }
  lines.push("=".repeat(70));
  lines.push(`Generated by Grant2Fund'n — ${new Date().toLocaleDateString("en-CA")}`);
  lines.push("=".repeat(70));
  return lines.join("\n");
}

async function buildPDF(grant: any): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const pageWidth = 612;
  const pageHeight = 792;
  const margin = 60;
  const contentWidth = pageWidth - margin * 2;

  function addPage() {
    const p = pdfDoc.addPage([pageWidth, pageHeight]);
    return { page: p, y: pageHeight - margin };
  }

  function wrapText(text: string, font: any, fontSize: number, maxWidth: number): string[] {
    const result: string[] = [];
    // Split on hard newlines first, then word-wrap each paragraph
    for (const paragraph of text.split(/\r?\n/)) {
      if (!paragraph.trim()) { result.push(""); continue; }
      const words = paragraph.split(" ");
      let current = "";
      for (const word of words) {
        // Strip any remaining control characters pdf-lib can't encode
        const safeWord = word.replace(/[^\x20-\x7E]/g, "");
        if (!safeWord) continue;
        const test = current ? `${current} ${safeWord}` : safeWord;
        if (font.widthOfTextAtSize(test, fontSize) > maxWidth && current) {
          result.push(current);
          current = safeWord;
        } else {
          current = test;
        }
      }
      if (current) result.push(current);
    }
    return result;
  }

  let { page, y } = addPage();

  function drawText(text: string, font: any, size: number, color = rgb(0, 0, 0), indent = 0) {
    const lines = wrapText(text, font, size, contentWidth - indent);
    for (const line of lines) {
      if (y < margin + 40) {
        ({ page, y } = addPage());
      }
      y -= size + 4;
      page.drawText(line, { x: margin + indent, y, font, size, color });
    }
  }

  // Title
  drawText(grant.title, boldFont, 18);
  y -= 6;
  drawText(`Applicant: ${grant.organization.name}`, regularFont, 11, rgb(0.3, 0.3, 0.3));
  drawText(`Funder: ${grant.funder.name}`, regularFont, 11, rgb(0.3, 0.3, 0.3));
  if (grant.requestedAmount) drawText(`Amount Requested: $${Number(grant.requestedAmount).toLocaleString("en-CA")}`, regularFont, 11, rgb(0.3, 0.3, 0.3));
  if (grant.deadline) drawText(`Deadline: ${new Date(grant.deadline).toLocaleDateString("en-CA")}`, regularFont, 11, rgb(0.3, 0.3, 0.3));
  y -= 10;
  page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });
  y -= 16;

  for (const s of grant.sections) {
    if (!s.content) continue;
    drawText(s.label, boldFont, 13);
    y -= 4;
    drawText(s.content, regularFont, 10, rgb(0.2, 0.2, 0.2));
    y -= 2;
    drawText(`${s.wordCount} words`, regularFont, 8, rgb(0.6, 0.6, 0.6));
    y -= 10;
    page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: rgb(0.9, 0.9, 0.9) });
    y -= 14;
  }

  drawText(`Generated by Grant2Fund'n — ${new Date().toLocaleDateString("en-CA")}`, regularFont, 8, rgb(0.7, 0.7, 0.7));

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}

async function buildDocx(grant: any): Promise<Buffer> {
  const children: Paragraph[] = [];

  children.push(new Paragraph({
    text: grant.title,
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
  }));

  children.push(new Paragraph({
    children: [new TextRun({ text: `Applicant: ${grant.organization.name}`, size: 22 })],
    alignment: AlignmentType.CENTER,
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: `Funder: ${grant.funder.name}`, size: 22 })],
    alignment: AlignmentType.CENTER,
  }));
  if (grant.requestedAmount) {
    children.push(new Paragraph({
      children: [new TextRun({ text: `Amount Requested: $${Number(grant.requestedAmount).toLocaleString("en-CA")}`, size: 22 })],
      alignment: AlignmentType.CENTER,
    }));
  }
  if (grant.deadline) {
    children.push(new Paragraph({
      children: [new TextRun({ text: `Deadline: ${new Date(grant.deadline).toLocaleDateString("en-CA")}`, size: 22 })],
      alignment: AlignmentType.CENTER,
    }));
  }

  children.push(new Paragraph({ text: "" }));

  for (const s of grant.sections) {
    if (!s.content) continue;
    children.push(new Paragraph({ text: s.label, heading: HeadingLevel.HEADING_2 }));
    children.push(new Paragraph({ children: [new TextRun({ text: s.content, size: 22 })] }));
    children.push(new Paragraph({
      children: [new TextRun({ text: `${s.wordCount} words`, size: 18, color: "999999", italics: true })],
    }));
    children.push(new Paragraph({ text: "" }));
  }

  children.push(new Paragraph({
    children: [new TextRun({
      text: `Generated by Grant2Fund'n — ${new Date().toLocaleDateString("en-CA")}`,
      size: 18, color: "aaaaaa", italics: true,
    })],
    alignment: AlignmentType.CENTER,
  }));

  const doc = new Document({ sections: [{ children }] });
  return await Packer.toBuffer(doc);
}
